version: "3.4"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /sessions
    depends_on:
      - db
  db:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: ah83is82js95pq
      MYSQL_DATABASE: northernairport
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    restart: always
  app:
    container_name: NorthernAirport
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "443:443"
    restart: always
    volumes:
      - /data/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt-www:/tmp/lestencrypt