# syntax=docker/dockerfile:1

FROM golang:1.16-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY * ./
COPY templates/* ./templates/

RUN go build -o /docker-gs-ping

#RUN apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev rust cargo
#RUN pip3 install pip --upgrade
#RUN pip3 install certbot-nginx
#RUN mkdir /etc/letsencrypt

USER root

RUN apk update
RUN apk add python3 python3-dev py3-pip build-base libressl-dev gcc musl-dev py3-virtualenv augeas libffi-dev rust cargo
RUN python3 -m venv /opt/certbot/
RUN source /opt/certbot/bin/activate
RUN /opt/certbot/bin/pip install --upgrade pip
RUN /opt/certbot/bin/pip install certbot
RUN ln -s /opt/certbot/bin/certbot /usr/bin/certbot
RUN certbot -v certonly --webroot --agree-tos --renew-by-default \
    --preferred-challenges http-01 --server https://acme-v02.api.letsencrypt.org/directory \
    --text --email matt@mgrenier.ca \
    -w /tmp/letsencrypt -d northerair.xyz

EXPOSE 8080

CMD [ "/docker-gs-ping" ]