version: "3.4"

services:
  db:
    image: mysql:8.0.16
    environment: 
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: northernairport
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  web:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
volumes:
  data:
    external: false
    